version: "3.6"
services:
  tf2-server:
    image: cm2network/tf2:sourcemod
    network_mode: "host"
    volumes:
      - cfg:/home/steam/tf2-dedicated/tf/cfg
      - addons:/home/steam/tf2-dedicated/tf/addons
    env_file:
      - ./.env
      - .secret.env

  ftpd_server:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - cfg:/home/admin/cfg
      - addons:/home/admin/addons
      - ftp-user-data:/home/ftpusers/
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: admin
      FTP_USER_HOME: /home/admin
    env_file:
      - .secret.env
    restart: always

volumes:
  cfg:
  addons:
  ftp-user-data:
